<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/190722/1-1ZH21K231.jpg ",93,236);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/190722/1-1ZH21K231.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="5184";
$z[1][4]['height']="3456";
$z[2]=Array("img"," /uploads/allimg/190722/1-1ZH21K233.jpg ",238,381);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/190722/1-1ZH21K233.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="4896";
$z[2][4]['height']="2712";
$z[3]=Array("img"," /uploads/allimg/190722/1-1ZH21K236.jpg ",383,526);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/190722/1-1ZH21K236.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="4758";
$z[3][4]['height']="2592";

?>