<li class="b-line">
						<h2>[field:title/]<span><i class="icon icon-add"></i>Source：Tarzan Instruments  Time：2015-05-01</span></h2>
						<p>
							<div>
								<div style="width: 15%;float: left;">[field:imglink/]</div>
								<div style="width: 85%;float: left;">
									[field:description/]...
									<a href="[field:arcurl/]">More</a>
								</div>
							</div>
						</p> 
						
					</li>