
				<li><a href='[field:typeurl/]'>[field:typename/]<span>></span></a></li> 
				{/dede:chann	{dede:list pagesize='6'}
	<div class="goods_item_list">
		<div class="goodlist_content">
			<a href="[field:arcurl/]"><img src="[field:litpic/]" alt="Hydraulic Cylinders"></a>
			<p class="good_title"><a href="[field:arcurl/]">[field:title/]</a></p>
			<p class="good_desc">[field:description/]</p>
			<p class="good_price">more</p>
		</div>
	</div>
	{/dede:list}
	
	
           {dede:list pagesize='12'}
				<li>
					<a href="[field:arcurl/]" class="pic"><img src="[field:litpic/]" alt="[field:title function='html2text(@me)'/]"/></a>
					<a href="[field:arcurl/]" class="title">[field:title/]</a>
					<span class="date"><small>最后更新：</small>[field:pubdate function="GetDateMK(@me)"/]</span>
				</li>
          {/dede:list}el} 				
			</ul>
		</div>

	
	
	
	</div>
	
	<div class="con_right">
	<div id="wzdh">
		<ul>
		<li>{dede:field name='position'/}</li>
		</ul>
	</div>
	

	
 
	<div class="pagination">
		<li>Index</li>
		<li class="thisclass">1</li>
		<li><a href='list_8_2.html'>2</a></li>
		<li><a href='list_8_3.html'>3</a></li>
		<li><a href='list_8_4.html'>4</a></li>
		<li><a href='list_8_2.html'>Next</a></li>
		<li><a href='list_8_4.html'>End</a></li> 
	</div>
	
	</div>

	<div class="cl"></div>
</div>

 
	
	<div class="cl"></div>
</div>
 

<footer>
	<ul>
		<li>
			<h2>关于我们</h2>
			{dede:channel typeid='2' type='son'}
			<a href='[field:typeurl/]'>[field:typename/]</a>
			