<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/190719/1-1ZG9213103.jpg ",93,264);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/190719/1-1ZG9213103.jpg";
$z[1][4]['text']="单作用薄型液压油缸";
$z[1][4]['width']="1200";
$z[1][4]['height']="878";
$z[2]=Array("img"," /uploads/allimg/190719/1-1ZG9213108.jpg ",266,436);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/190719/1-1ZG9213108.jpg";
$z[2][4]['text']="单作用薄型液压油缸";
$z[2][4]['width']="800";
$z[2][4]['height']="534";

?>