<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/190719/1-1ZG9212208.jpg ",93,284);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/190719/1-1ZG9212208.jpg";
$z[1][4]['text']="套筒，扭矩扳手套筒，输出方驱套筒";
$z[1][4]['width']="690";
$z[1][4]['height']="593";

?>