<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/190724/1-1ZH4201613.jpg ",93,261);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/190724/1-1ZH4201613.jpg";
$z[1][4]['text']="Hydraulic Flange Spreader";
$z[1][4]['width']="600";
$z[1][4]['height']="332";

?>