{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/190724/1-1ZH4195005.jpg' text='High pressure hydraulic hand pump' width='600' height='515'} /uploads/allimg/190724/1-1ZH4195005.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/190724/1-1ZH4195006.jpg' text='High pressure hydraulic hand pump' width='600' height='375'} /uploads/allimg/190724/1-1ZH4195006.jpg {/dede:img}
