<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/190724/1-1ZH4203358.jpg ",93,289);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/190724/1-1ZH4203358.jpg";
$z[1][4]['text']="Single acting low profile locknut hydraulic cylinders";
$z[1][4]['width']="600";
$z[1][4]['height']="430";
$z[2]=Array("img"," /uploads/allimg/190724/1-1ZH4203400.png ",291,487);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/190724/1-1ZH4203400.png";
$z[2][4]['text']="Single acting low profile locknut hydraulic cylinders";
$z[2][4]['width']="600";
$z[2][4]['height']="364";

?>