<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/190724/1-1ZH4205337.jpg ",93,276);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/190724/1-1ZH4205337.jpg";
$z[1][4]['text']="Single Acting Hollow Plunger Cylinders";
$z[1][4]['width']="600";
$z[1][4]['height']="565";
$z[2]=Array("img"," /uploads/allimg/190724/1-1ZH4205338.jpg ",278,461);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/190724/1-1ZH4205338.jpg";
$z[2][4]['text']="Single Acting Hollow Plunger Cylinders";
$z[2][4]['width']="600";
$z[2][4]['height']="400";
$z[3]=Array("img"," /uploads/allimg/190724/1-1ZH4205339.jpg ",463,646);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/190724/1-1ZH4205339.jpg";
$z[3][4]['text']="Single Acting Hollow Plunger Cylinders";
$z[3][4]['width']="600";
$z[3][4]['height']="400";

?>