<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/190723/1-1ZH3215P1.jpg ",93,253);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/190723/1-1ZH3215P1.jpg";
$z[1][4]['text']="Torque Multiplier";
$z[1][4]['width']="1936";
$z[1][4]['height']="1404";
$z[2]=Array("img"," /uploads/allimg/190723/1-1ZH3215P2.jpg ",255,415);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/190723/1-1ZH3215P2.jpg";
$z[2][4]['text']="Torque Multiplier";
$z[2][4]['width']="3264";
$z[2][4]['height']="2448";
$z[3]=Array("img"," /uploads/allimg/190723/1-1ZH3215P8.jpg ",417,577);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/190723/1-1ZH3215P8.jpg";
$z[3][4]['text']="Torque Multiplier";
$z[3][4]['width']="3920";
$z[3][4]['height']="2204";
$z[4]=Array("img"," /uploads/allimg/190723/1-1ZH3215Q1.jpg ",579,739);
$z[4][4]=array();
$z[4][4]['ddimg']="/uploads/allimg/190723/1-1ZH3215Q1.jpg";
$z[4][4]['text']="Torque Multiplier";
$z[4][4]['width']="3920";
$z[4][4]['height']="2204";

?>