{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/190718/1-1ZGR20245.jpg' text='' width='1200' height='800'} /uploads/allimg/190718/1-1ZGR20245.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/190718/1-1ZGR20245-50.jpg' text='' width='1200' height='998'} /uploads/allimg/190718/1-1ZGR20245-50.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/190718/1-1ZGR20405.png' text='' width='807' height='513'} /uploads/allimg/190718/1-1ZGR20405.png {/dede:img}
