
				<li><a href='[field:typeurl/]'>[field:typename/]<span>></span></a></li>  
			</ul>
		</div>

	
	
	
	</div>
	
	<div class="con_right">
	<div id="wzdh">
		<ul>
		<li>Position： <a href='/'>Home</a> > <a href='/'>Products</a> > Bolting Tools</li>
		</ul>
	</div>
	
	<div class="goods_item_list">
		<div class="goodlist_content">
			<a href="/"><img src="{dede:global.cfg_cmspath/}/static/images/1.jpg" alt="Hydraulic Cylinders"></a>
			<p class="good_title"><a href="/">Hydraulic Cylinders</a></p>
			<p class="good_desc">Hydraulic Cylinders</p>
			<p class="good_price">more</p>
		</div>
	</div>
	<div class="goods_item_list">
		<div class="goodlist_content">
			<a href="/"><img src="{dede:global.cfg_cmspath/}/static/images/1.jpg" alt="Hydraulic Cylinders"></a>
			<p class="good_title"><a href="/">Hydraulic Cylinders</a></p>
			<p class="good_desc">Hydraulic Cylinders</p>
			<p class="good_price">more</p>
		</div>
	</div>
	<div class="goods_item_list">
		<div class="goodlist_content">
			<a href="/"><img src="{dede:global.cfg_cmspath/}/static/images/1.jpg" alt="Hydraulic Cylinders"></a>
			<p class="good_title"><a href="/">Hydraulic Cylinders</a></p>
			<p class="good_desc">Hydraulic Cylinders</p>
			<p class="good_price">more</p>
		</div>
	</div>
	<div class="goods_item_list">
		<div class="goodlist_content">
			<a href="/"><img src="{dede:global.cfg_cmspath/}/static/images/1.jpg" alt="Hydraulic Cylinders"></a>
			<p class="good_title"><a href="/">Hydraulic Cylinders</a></p>
			<p class="good_desc">Hydraulic Cylinders</p>
			<p class="good_price">more</p>
		</div>
	</div>
	<div class="goods_item_list">
		<div class="goodlist_content">
			<a href="/"><img src="{dede:global.cfg_cmspath/}/static/images/1.jpg" alt="Hydraulic Cylinders"></a>
			<p class="good_title"><a href="/">Hydraulic Cylinders</a></p>
			<p class="good_desc">Hydraulic Cylinders</p>
			<p class="good_price">more</p>
		</div>
	</div>
	<div class="goods_item_list">
		<div class="goodlist_content">
			<a href="/"><img src="{dede:global.cfg_cmspath/}/static/images/1.jpg" alt="Hydraulic Cylinders"></a>
			<p class="good_title"><a href="/">Hydraulic Cylinders</a></p>
			<p class="good_desc">Hydraulic Cylinders</p>
			<p class="good_price">more</p>
		</div>
	</div>
	
	<div class="pagination">
		<li>Index</li>
		<li class="thisclass">1</li>
		<li><a href='list_8_2.html'>2</a></li>
		<li><a href='list_8_3.html'>3</a></li>
		<li><a href='list_8_4.html'>4</a></li>
		<li><a href='list_8_2.html'>Next</a></li>
		<li><a href='list_8_4.html'>End</a></li> 
	</div>
	
	</div>

	<div class="cl"></div>
</div>

 
	
	<div class="cl"></div>
</div>
 

<footer>
	<ul>
		<li>
			<h2>关于我们</h2>
			{dede:channel typeid='2' type='son'}
			<a href='[field:typeurl/]'>[field:typename/]</a>
			