<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/190723/1-1ZH3220203.jpg ",93,249);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/190723/1-1ZH3220203.jpg";
$z[1][4]['text']="Hydraulic Nut";
$z[1][4]['width']="600";
$z[1][4]['height']="500";

?>