<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/190724/1-1ZH4211544.jpg ",93,284);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/190724/1-1ZH4211544.jpg";
$z[1][4]['text']="Double Acting Hollow Plunger Hydraulic Cylinders";
$z[1][4]['width']="600";
$z[1][4]['height']="400";
$z[2]=Array("img"," /uploads/allimg/190724/1-1ZH4211545.jpg ",286,477);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/190724/1-1ZH4211545.jpg";
$z[2][4]['text']="Double Acting Hollow Plunger Hydraulic Cylinders";
$z[2][4]['width']="600";
$z[2][4]['height']="400";
$z[3]=Array("img"," /uploads/allimg/190724/1-1ZH4211620.jpg ",479,670);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/190724/1-1ZH4211620.jpg";
$z[3][4]['text']="Double Acting Hollow Plunger Hydraulic Cylinders";
$z[3][4]['width']="600";
$z[3][4]['height']="894";

?>