<li class="b-line">
						<h2>[field:title/]<span><i class="icon icon-add"></i>Source：Tarzan Instruments  Time：2015-05-01</span></h2>
						<p>
						<table width="100%" border="0" cellspacing="2" cellpadding="2">
						  <tbody><tr> 
						    <td width="20%" align="left" >[field:imglink/]</td>
						    <td width="80%">[field:description/]...<br/><br/><a href="[field:arcurl/]">More</a></td>
						  </tr>
						</tbody></table>
						</p> 
						
					</li>