<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/190719/1-1ZG9211059.jpg ",93,258);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/190719/1-1ZG9211059.jpg";
$z[1][4]['text']="液压螺栓拉伸器";
$z[1][4]['width']="852";
$z[1][4]['height']="1136";
$z[2]=Array("img"," /uploads/allimg/190719/1-1ZG9211059-50.jpg ",260,431);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/190719/1-1ZG9211059-50.jpg";
$z[2][4]['text']="液压螺栓拉伸器";
$z[2][4]['width']="852";
$z[2][4]['height']="1136";
$z[3]=Array("img"," /uploads/allimg/190719/1-1ZG9211059-51.jpg ",433,604);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/190719/1-1ZG9211059-51.jpg";
$z[3][4]['text']="液压螺栓拉伸器";
$z[3][4]['width']="1200";
$z[3][4]['height']="900";
$z[4]=Array("img"," /uploads/allimg/190719/1-1ZG9211059-52.jpg ",606,778);
$z[4][4]=array();
$z[4][4]['ddimg']="/uploads/allimg/190719/1-1ZG9211059-52.jpg";
$z[4][4]['text']="液压螺栓拉伸器";
$z[4][4]['width']="1200";
$z[4][4]['height']="1031";

?>