{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/190719/1-1ZG9211059.jpg' text='液压螺栓拉伸器' width='852' height='1136'} /uploads/allimg/190719/1-1ZG9211059.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/190719/1-1ZG9211059-50.jpg' text='液压螺栓拉伸器' width='852' height='1136'} /uploads/allimg/190719/1-1ZG9211059-50.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/190719/1-1ZG9211059-51.jpg' text='液压螺栓拉伸器' width='1200' height='900'} /uploads/allimg/190719/1-1ZG9211059-51.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/190719/1-1ZG9211059-52.jpg' text='液压螺栓拉伸器' width='1200' height='1031'} /uploads/allimg/190719/1-1ZG9211059-52.jpg {/dede:img}
