<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/190724/1-1ZH4195405.jpg ",93,256);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/190724/1-1ZH4195405.jpg";
$z[1][4]['text']="Hydraulic hand pump";
$z[1][4]['width']="600";
$z[1][4]['height']="365";
$z[2]=Array("img"," /uploads/allimg/190724/1-1ZH4195405-50.jpg ",258,427);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/190724/1-1ZH4195405-50.jpg";
$z[2][4]['text']="Hydraulic hand pump";
$z[2][4]['width']="600";
$z[2][4]['height']="271";

?>