{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/190724/1-1ZH4195405.jpg' text='Hydraulic hand pump ' width='600' height='365'} /uploads/allimg/190724/1-1ZH4195405.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/190724/1-1ZH4195405-50.jpg' text='Hydraulic hand pump ' width='600' height='271'} /uploads/allimg/190724/1-1ZH4195405-50.jpg {/dede:img}
