<div class="newsc_list">
  		<div class="newsc_list_pic">
  			<a href="[field:arcurl/]"><img src="[field:litpic/]"/></a>
  		</div>
  		<div class="newsc_detail">
  			<h3><a href="[field:arcurl/]">[field:title/]</a></h3>
  			<h4>[field:pubdate function="MyDate('m-d',@me)"/]</h4>
  			<a href="[field:arcurl/]">[field:description function='cn_substr(@me,60)'/]...</a>
  		</div>
  		<div class="clear"></div>
  	</div>