<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/190719/1-1ZG9213326.jpg ",93,264);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/190719/1-1ZG9213326.jpg";
$z[1][4]['text']="单作用超低薄型油缸";
$z[1][4]['width']="1200";
$z[1][4]['height']="554";
$z[2]=Array("img"," /uploads/allimg/190719/1-1ZG9213326-50.jpg ",266,443);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/190719/1-1ZG9213326-50.jpg";
$z[2][4]['text']="单作用超低薄型油缸";
$z[2][4]['width']="1200";
$z[2][4]['height']="665";
$z[3]=Array("img"," /uploads/allimg/190719/1-1ZG9213326-51.jpg ",445,622);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/190719/1-1ZG9213326-51.jpg";
$z[3][4]['text']="单作用超低薄型油缸";
$z[3][4]['width']="1200";
$z[3][4]['height']="561";

?>