<li class="b-line">
						<h2>[field:title/]<span><i class="icon icon-add"></i>Source：Tarzan Instruments  Time：2015-05-01</span></h2>
						<p>
						<table width="100%" border="0" cellspacing="2" cellpadding="2">
						  <tbody><tr> 
						    <td width="30%" rowspan="2" align="center">[field:imglink/]</td>
						    <td width="70%">[field:description/]...</a></td>
						  </tr>
						</tbody></table>
						</p> 
						<a href="[field:arcurl/]">More</a>
					</li>