<div class="newsc_list">
  		<div class="newsc_list_pic">
  			<a href="[field:arcurl/]"><img src="statics/images/201807131300052720.jpg"/></a>
  		</div>
  		<div class="newsc_detail">
  			<h3><a href="news-view.html">[field:title/]</a></h3>
  			<h4>[field:pubdate function="MyDate('m-d',@me)"/]</h4>
  			<a href="[field:arcurl/]">[field:description/]...</a>
  		</div>
  		<div class="clear"></div>
  	</div>