{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/190722/1-1ZH21I045.jpg' text='双作用大吨位油缸' width='2632' height='3100'} /uploads/allimg/190722/1-1ZH21I045.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/190722/1-1ZH21I046.jpg' text='双作用大吨位油缸' width='2876' height='3172'} /uploads/allimg/190722/1-1ZH21I046.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/190722/1-1ZH21I047.jpg' text='双作用大吨位油缸' width='3822' height='3360'} /uploads/allimg/190722/1-1ZH21I047.jpg {/dede:img}
