{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/190723/1-1ZH3225058.jpg' text='Vehicle loaded hydraulic puller' width='700' height='468'} /uploads/allimg/190723/1-1ZH3225058.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/190723/1-1ZH3225059.jpg' text='Vehicle loaded hydraulic puller' width='700' height='505'} /uploads/allimg/190723/1-1ZH3225059.jpg {/dede:img}
