<li><a href="[field:arcurl/]" target="_blank"><img src="[field:litpic/]" /></a>
              <div class="advantage_content">
                <div class="advantage_title">
                  <h2>[field:title/]</h2>
                  <!-- <h3></h3> -->
                </div>              
                <div class="advantage_detail">
                  <p>[field:info/]</p>
				</div>
              </div>
          </li>