<?php
$z[0]=Array("arcurl","",74,89);
$z[0][4]=array();
$z[1]=Array("litpic","",101,116);
$z[1][4]=array();
$z[2]=Array("title","",203,217);
$z[2][4]=array();
$z[3]=Array("pubdate","",237,282);
$z[3][4]=array();
$z[3][4]['function']="MyDate('m-d',@me)";
$z[4]=Array("arcurl","",303,318);
$z[4][4]=array();
$z[5]=Array("description","",320,369);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me,60)";

?>