<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/190723/1-1ZH3203U7.jpg ",93,256);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/190723/1-1ZH3203U7.jpg";
$z[1][4]['text']="车载液压拔轮器";
$z[1][4]['width']="1022";
$z[1][4]['height']="684";
$z[2]=Array("img"," /uploads/allimg/190723/1-1ZH3204107.jpg ",258,422);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/190723/1-1ZH3204107.jpg";
$z[2][4]['text']="车载液压拔轮器";
$z[2][4]['width']="772";
$z[2][4]['height']="557";

?>