<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/190724/1-1ZH4205044.jpg ",93,269);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/190724/1-1ZH4205044.jpg";
$z[1][4]['text']="Single Acting Hydraulic Cylinders";
$z[1][4]['width']="600";
$z[1][4]['height']="603";
$z[2]=Array("img"," /uploads/allimg/190724/1-1ZH4205046.jpg ",271,447);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/190724/1-1ZH4205046.jpg";
$z[2][4]['text']="Single Acting Hydraulic Cylinders";
$z[2][4]['width']="600";
$z[2][4]['height']="845";
$z[3]=Array("img"," /uploads/allimg/190724/1-1ZH4205047.jpg ",449,625);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/190724/1-1ZH4205047.jpg";
$z[3][4]['text']="Single Acting Hydraulic Cylinders";
$z[3][4]['width']="600";
$z[3][4]['height']="399";
$z[4]=Array("img"," /uploads/allimg/190724/1-1ZH4205048.jpg ",627,803);
$z[4][4]=array();
$z[4][4]['ddimg']="/uploads/allimg/190724/1-1ZH4205048.jpg";
$z[4][4]['text']="Single Acting Hydraulic Cylinders";
$z[4][4]['width']="600";
$z[4][4]['height']="527";

?>