<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/190723/1-1ZH3222933.png ",93,278);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/190723/1-1ZH3222933.png";
$z[1][4]['text']="Low Profile Hollow Hydraulic Torque Wrench";
$z[1][4]['width']="600";
$z[1][4]['height']="450";
$z[2]=Array("img"," /uploads/allimg/190723/1-1ZH3222934.jpg ",280,465);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/190723/1-1ZH3222934.jpg";
$z[2][4]['text']="Low Profile Hollow Hydraulic Torque Wrench";
$z[2][4]['width']="700";
$z[2][4]['height']="467";
$z[3]=Array("img"," /uploads/allimg/190723/1-1ZH3222935.jpg ",467,652);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/190723/1-1ZH3222935.jpg";
$z[3][4]['text']="Low Profile Hollow Hydraulic Torque Wrench";
$z[3][4]['width']="700";
$z[3][4]['height']="467";
$z[4]=Array("img"," /uploads/allimg/190723/1-1ZH3222935-50.jpg ",654,845);
$z[4][4]=array();
$z[4][4]['ddimg']="/uploads/allimg/190723/1-1ZH3222935-50.jpg";
$z[4][4]['text']="Low Profile Hollow Hydraulic Torque Wrench";
$z[4][4]['width']="700";
$z[4][4]['height']="467";

?>