<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/190723/1-1ZH3223401.jpg ",93,288);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/190723/1-1ZH3223401.jpg";
$z[1][4]['text']="Square Drive Hydraulic Torque Wrench ( Al-Ti alloy )";
$z[1][4]['width']="700";
$z[1][4]['height']="525";
$z[2]=Array("img"," /uploads/allimg/190723/1-1ZH3223402.jpg ",290,485);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/190723/1-1ZH3223402.jpg";
$z[2][4]['text']="Square Drive Hydraulic Torque Wrench ( Al-Ti alloy )";
$z[2][4]['width']="700";
$z[2][4]['height']="467";
$z[3]=Array("img"," /uploads/allimg/190723/1-1ZH3223403.jpg ",487,682);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/190723/1-1ZH3223403.jpg";
$z[3][4]['text']="Square Drive Hydraulic Torque Wrench ( Al-Ti alloy )";
$z[3][4]['width']="700";
$z[3][4]['height']="525";
$z[4]=Array("img"," /uploads/allimg/190723/1-1ZH3223404.jpg ",684,879);
$z[4][4]=array();
$z[4][4]['ddimg']="/uploads/allimg/190723/1-1ZH3223404.jpg";
$z[4][4]['text']="Square Drive Hydraulic Torque Wrench ( Al-Ti alloy )";
$z[4][4]['width']="700";
$z[4][4]['height']="933";

?>