<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/190723/1-1ZH3222513.jpg ",93,273);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/190723/1-1ZH3222513.jpg";
$z[1][4]['text']="Square Drive Hydraulic Torque Wrench";
$z[1][4]['width']="700";
$z[1][4]['height']="570";
$z[2]=Array("img"," /uploads/allimg/190723/1-1ZH3222514.jpg ",275,455);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/190723/1-1ZH3222514.jpg";
$z[2][4]['text']="Square Drive Hydraulic Torque Wrench";
$z[2][4]['width']="700";
$z[2][4]['height']="525";
$z[3]=Array("img"," /uploads/allimg/190723/1-1ZH3222514-50.jpg ",457,643);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/190723/1-1ZH3222514-50.jpg";
$z[3][4]['text']="Square Drive Hydraulic Torque Wrench";
$z[3][4]['width']="700";
$z[3][4]['height']="458";
$z[4]=Array("img"," /uploads/allimg/190723/1-1ZH3222515.jpg ",645,825);
$z[4][4]=array();
$z[4][4]['ddimg']="/uploads/allimg/190723/1-1ZH3222515.jpg";
$z[4][4]['text']="Square Drive Hydraulic Torque Wrench";
$z[4][4]['width']="700";
$z[4][4]['height']="340";

?>