<li><a href="[field:arcurl/]" target="_blank"><img src="[field:litpic/]" /></a>
              <div class="advantage_content">
                <div class="advantage_title">
                  <h2><a href="[field:arcurl/]">[field:title/]</a></h2>
                  <!-- <h3></h3> -->
                </div>              
                <div class="advantage_detail">
                  <p><a href="[field:arcurl/]">[field:info/]</a></p>
				</div>
              </div>
          </li>