<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/190722/1-1ZH21J329.jpg ",93,236);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/190722/1-1ZH21J329.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="4038";
$z[1][4]['height']="3378";
$z[2]=Array("img"," /uploads/allimg/190722/1-1ZH21J330.jpg ",238,381);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/190722/1-1ZH21J330.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1842";
$z[2][4]['height']="3288";

?>