{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/190724/1-1ZH4200R3.jpg' text='Manual hydraulic pump' width='600' height='332'} /uploads/allimg/190724/1-1ZH4200R3.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/190724/1-1ZH4200R3-50.jpg' text='Manual hydraulic pump' width='600' height='400'} /uploads/allimg/190724/1-1ZH4200R3-50.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/190724/1-1ZH4200R4.jpg' text='Manual hydraulic pump' width='600' height='327'} /uploads/allimg/190724/1-1ZH4200R4.jpg {/dede:img}
