<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/190724/1-1ZH4200R3.jpg ",93,255);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/190724/1-1ZH4200R3.jpg";
$z[1][4]['text']="Manual hydraulic pump";
$z[1][4]['width']="600";
$z[1][4]['height']="332";
$z[2]=Array("img"," /uploads/allimg/190724/1-1ZH4200R3-50.jpg ",257,425);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/190724/1-1ZH4200R3-50.jpg";
$z[2][4]['text']="Manual hydraulic pump";
$z[2][4]['width']="600";
$z[2][4]['height']="400";
$z[3]=Array("img"," /uploads/allimg/190724/1-1ZH4200R4.jpg ",427,589);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/190724/1-1ZH4200R4.jpg";
$z[3][4]['text']="Manual hydraulic pump";
$z[3][4]['width']="600";
$z[3][4]['height']="327";

?>