<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/190723/1-1ZH3222139.png ",93,287);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/190723/1-1ZH3222139.png";
$z[1][4]['text']="Large Capacity Square Drive Hydraulic Torque Wrench";
$z[1][4]['width']="700";
$z[1][4]['height']="451";
$z[2]=Array("img"," /uploads/allimg/190723/1-1ZH3222139-50.png ",289,489);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/190723/1-1ZH3222139-50.png";
$z[2][4]['text']="Large Capacity Square Drive Hydraulic Torque Wrench";
$z[2][4]['width']="600";
$z[2][4]['height']="343";
$z[3]=Array("img"," /uploads/allimg/190723/1-1ZH3222140.png ",491,685);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/190723/1-1ZH3222140.png";
$z[3][4]['text']="Large Capacity Square Drive Hydraulic Torque Wrench";
$z[3][4]['width']="700";
$z[3][4]['height']="525";

?>