<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/190723/1-1ZH3210459.jpg ",93,256);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/190723/1-1ZH3210459.jpg";
$z[1][4]['text']="钢丝绳压套机";
$z[1][4]['width']="3260";
$z[1][4]['height']="2644";
$z[2]=Array("img"," /uploads/allimg/190723/1-1ZH3210459.png ",258,419);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/190723/1-1ZH3210459.png";
$z[2][4]['text']="钢丝绳压套机";
$z[2][4]['width']="512";
$z[2][4]['height']="467";
$z[3]=Array("img"," /uploads/allimg/190723/1-1ZH3210501.jpg ",421,584);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/190723/1-1ZH3210501.jpg";
$z[3][4]['text']="钢丝绳压套机";
$z[3][4]['width']="3456";
$z[3][4]['height']="3648";

?>