{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/190723/1-1ZH3210459.jpg' text='钢丝绳压套机' width='3260' height='2644'} /uploads/allimg/190723/1-1ZH3210459.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/190723/1-1ZH3210459.png' text='钢丝绳压套机' width='512' height='467'} /uploads/allimg/190723/1-1ZH3210459.png {/dede:img}
{dede:img ddimg='/uploads/allimg/190723/1-1ZH3210501.jpg' text='钢丝绳压套机' width='3456' height='3648'} /uploads/allimg/190723/1-1ZH3210501.jpg {/dede:img}
