<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/190724/1-1ZH4193R5.jpg ",93,264);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/190724/1-1ZH4193R5.jpg";
$z[1][4]['text']="Electric Hydraulic Wrench Pump";
$z[1][4]['width']="600";
$z[1][4]['height']="499";
$z[2]=Array("img"," /uploads/allimg/190724/1-1ZH4193R6.jpg ",266,437);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/190724/1-1ZH4193R6.jpg";
$z[2][4]['text']="Electric Hydraulic Wrench Pump";
$z[2][4]['width']="600";
$z[2][4]['height']="400";
$z[3]=Array("img"," /uploads/allimg/190724/1-1ZH4193R6-50.jpg ",439,616);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/190724/1-1ZH4193R6-50.jpg";
$z[3][4]['text']="Electric Hydraulic Wrench Pump";
$z[3][4]['width']="600";
$z[3][4]['height']="530";
$z[4]=Array("img"," /uploads/allimg/190724/1-1ZH4193R7.jpg ",618,789);
$z[4][4]=array();
$z[4][4]['ddimg']="/uploads/allimg/190724/1-1ZH4193R7.jpg";
$z[4][4]['text']="Electric Hydraulic Wrench Pump";
$z[4][4]['width']="600";
$z[4][4]['height']="400";

?>