{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/190724/1-1ZH4202602.jpg' text='Hydraulic Swaging Machine' width='600' height='633'} /uploads/allimg/190724/1-1ZH4202602.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/190724/1-1ZH4202603.jpg' text='Hydraulic Swaging Machine' width='600' height='547'} /uploads/allimg/190724/1-1ZH4202603.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/190724/1-1ZH4202605.jpg' text='Hydraulic Swaging Machine' width='600' height='487'} /uploads/allimg/190724/1-1ZH4202605.jpg {/dede:img}
