<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/190724/1-1ZH4202602.jpg ",93,261);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/190724/1-1ZH4202602.jpg";
$z[1][4]['text']="Hydraulic Swaging Machine";
$z[1][4]['width']="600";
$z[1][4]['height']="633";
$z[2]=Array("img"," /uploads/allimg/190724/1-1ZH4202603.jpg ",263,431);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/190724/1-1ZH4202603.jpg";
$z[2][4]['text']="Hydraulic Swaging Machine";
$z[2][4]['width']="600";
$z[2][4]['height']="547";
$z[3]=Array("img"," /uploads/allimg/190724/1-1ZH4202605.jpg ",433,601);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/190724/1-1ZH4202605.jpg";
$z[3][4]['text']="Hydraulic Swaging Machine";
$z[3][4]['width']="600";
$z[3][4]['height']="487";

?>