<?php
$z[0]=Array("channel","\r\n			<a href='[field:typeurl/]'>[field:typename/]</a>\r\n			",50,160);
$z[0][4]=array();
$z[0][4]['typeid']="71";
$z[0][4]['type']="son";
$z[1]=Array("channel","\r\n			<a href='[field:typeurl/]'>[field:typename/]</a>\r\n			",205,315);
$z[1][4]=array();
$z[1][4]['typeid']="80";
$z[1][4]['type']="son";
$z[2]=Array("channel","\r\n			<a href='[field:typeurl/]'>[field:typename/]</a>\r\n			",366,477);
$z[2][4]=array();
$z[2][4]['typeid']="119";
$z[2][4]['type']="son";
$z[3]=Array("channel","\r\n			<a href='[field:typeurl/]'>[field:typename/]</a>\r\n			",521,632);
$z[3][4]=array();
$z[3][4]['typeid']="126";
$z[3][4]['type']="son";
$z[4]=Array("global","",690,716);
$z[4][4]=array();
$z[4][4]['name']="cfg_cmspath";
$z[5]=Array("global","",785,811);
$z[5][4]=array();
$z[5][4]['name']="cfg_cmspath";

?>