<?php
$z[0]=Array("type","[field:typelink /]",958,1010);
$z[0][4]=array();
$z[0][4]['typeid']="2";
$z[1]=Array("type","[field:typelink /]",1064,1117);
$z[1][4]=array();
$z[1][4]['typeid']="11";
$z[2]=Array("type","[field:typelink /]",1171,1224);
$z[2][4]=array();
$z[2][4]['typeid']="52";
$z[3]=Array("type","[field:typelink /]",1279,1332);
$z[3][4]=array();
$z[3][4]['typeid']="59";
$z[4]=Array("type","[field:typelink /]",1386,1439);
$z[4][4]=array();
$z[4][4]['typeid']="63";
$z[5]=Array("type","[field:typelink /]",1493,1546);
$z[5][4]=array();
$z[5][4]['typeid']="66";
$z[6]=Array("type","[field:typelink /]",1600,1653);
$z[6][4]=array();
$z[6][4]['typeid']="69";
$z[7]=Array("global","",1812,1838);
$z[7][4]=array();
$z[7][4]['name']="cfg_cmspath";

?>