<?php
$z[0]=Array("channel","\r\n			<a href='[field:typeurl/]'>[field:typename/]</a>\r\n			",54,163);
$z[0][4]=array();
$z[0][4]['typeid']="2";
$z[0][4]['type']="son";
$z[1]=Array("channel","\r\n			<a href='[field:typeurl/]'>[field:typename/]</a>\r\n			",212,322);
$z[1][4]=array();
$z[1][4]['typeid']="11";
$z[1][4]['type']="son";
$z[2]=Array("channel","\r\n			<a href='[field:typeurl/]'>[field:typename/]</a>\r\n			",383,493);
$z[2][4]=array();
$z[2][4]['typeid']="52";
$z[2][4]['type']="son";
$z[3]=Array("channel","\r\n			<a href='[field:typeurl/]'>[field:typename/]</a>\r\n			",551,661);
$z[3][4]=array();
$z[3][4]['typeid']="59";
$z[3][4]['type']="son";
$z[4]=Array("global","",721,747);
$z[4][4]=array();
$z[4][4]['name']="cfg_cmspath";
$z[5]=Array("global","",816,842);
$z[5][4]=array();
$z[5][4]['name']="cfg_cmspath";

?>