<?php
$z[0]=Array("type","[field:typelink /]",1016,1068);
$z[0][4]=array();
$z[0][4]['typeid']="2";
$z[1]=Array("type","[field:typelink /]",1108,1161);
$z[1][4]=array();
$z[1][4]['typeid']="11";
$z[2]=Array("type","[field:typelink /]",1201,1254);
$z[2][4]=array();
$z[2][4]['typeid']="52";
$z[3]=Array("type","[field:typelink /]",1295,1348);
$z[3][4]=array();
$z[3][4]['typeid']="59";
$z[4]=Array("type","[field:typelink /]",1388,1441);
$z[4][4]=array();
$z[4][4]['typeid']="63";
$z[5]=Array("type","[field:typelink /]",1481,1534);
$z[5][4]=array();
$z[5][4]['typeid']="66";
$z[6]=Array("type","[field:typelink /]",1574,1627);
$z[6][4]=array();
$z[6][4]['typeid']="69";
$z[7]=Array("global","",1757,1783);
$z[7][4]=array();
$z[7][4]['name']="cfg_cmspath";
$z[8]=Array("global","",1881,1907);
$z[8][4]=array();
$z[8][4]['name']="cfg_cmspath";
$z[9]=Array("global","",1998,2024);
$z[9][4]=array();
$z[9][4]['name']="cfg_cmspath";

?>