<?php
$z[0]=Array("type","[field:typelink /]",1011,1064);
$z[0][4]=array();
$z[0][4]['typeid']="71";
$z[1]=Array("type","[field:typelink /]",1097,1150);
$z[1][4]=array();
$z[1][4]['typeid']="80";
$z[2]=Array("type","[field:typelink /]",1186,1240);
$z[2][4]=array();
$z[2][4]['typeid']="119";
$z[3]=Array("type","[field:typelink /]",1281,1335);
$z[3][4]=array();
$z[3][4]['typeid']="126";
$z[4]=Array("type","[field:typelink /]",1370,1424);
$z[4][4]=array();
$z[4][4]['typeid']="130";
$z[5]=Array("type","[field:typelink /]",1456,1510);
$z[5][4]=array();
$z[5][4]['typeid']="133";
$z[6]=Array("type","[field:typelink /]",1545,1599);
$z[6][4]=array();
$z[6][4]['typeid']="136";
$z[7]=Array("global","",1722,1748);
$z[7][4]=array();
$z[7][4]['name']="cfg_cmspath";
$z[8]=Array("global","",1846,1872);
$z[8][4]=array();
$z[8][4]['name']="cfg_cmspath";
$z[9]=Array("global","",1963,1989);
$z[9][4]=array();
$z[9][4]['name']="cfg_cmspath";

?>